### ISSUE TITLE
Color is unreadable with a light terminal theme

### ISSUE THREAD

**Issue by wildwestrom** [museun/cargo-whatfeatures#71]
I don't think this is acceptable. Can you please output colors that are actually readable on every terminal?
For now I'll use `--color never`.

Thank you.

![image](https://github.com/museun/cargo-whatfeatures/assets/77174844/564906a8-c659-4525-93e5-b6f87734e022)

**Comment by wildwestrom** [comment]
That is one solution, however I believe more fundamentally the application should by default output only default terminal color codes so they adapt to the user's theme.

In the case of the Yansi library, that would be all `Color` variants other than `Fixed` or `RGB` while avoiding  `Black` and `White`, instead preferring the other colors as they are adjusted for contrast in any good theme.
```
Default
Black
Red
Green
Yellow
Blue
Magenta
Cyan
White
```

In fact I'd prefer prioritizing this over having configuration.

**Comment by museun** [comment]
I can add a palette flag that uses the vt stand for 16 colors user palette

**Comment by museun** [comment]
If you can try out the colors (its on 87be5d26bff7c083d4b7786b75f9afc20df29cb1 e.g. HEAD) before I publish it, I'd appreciate it.

**Comment by wildwestrom** [comment]
![20240221_15h05m59s_grim](https://github.com/museun/cargo-whatfeatures/assets/77174844/91432a8b-27ed-4907-978b-fe1cc166ac20)
Seems to be working well now on my machine.

**Comment by museun** [comment]
Thanks, I've published `v0.9.9` which defaults to the palette-based theme and includes the env-var override at `WHATFEATURES_THEME`

I wrote the coloring part of this 4+ years ago and never considered what it'd look like on other machines. I normally use `NO_COLOR` so this was definitely an oversight.
