### ISSUE TITLE
Text not visible on white background

### ISSUE THREAD

**Issue by nk9** [museun/cargo-whatfeatures#74]
I installed the crate:

```
cargo install cargo-whatfeatures
```

And ran it, but the output is not legible. It appears to assume you're using a term with a dark background:

<img width="363" alt="image" src="https://github.com/museun/cargo-whatfeatures/assets/3646730/50fc0ebd-bbb1-4994-86d4-f04773bfd83b">

Suggestions:
- In a perfect world, the CWF would know whether the terminal was using a light or dark background and prepare output colors accordingly. Sadly, this [does not appear to be straightforward](https://unix.stackexchange.com/a/245568/276057).
- Regardless of the nice auto-switching above, it should be possible to override the colors. So it would be good to have `--dark-background` and `--light-background`, or maybe just `--light` and `--dark` to set the text theme.
- It should also be possible to turn off colors entirely, which would let the terminal do something sensible by default. So some kind of rc file setting. I see that you support `NO_COLOR`, which is great, but I don't want NO_COLOR generally. I'd only be using it to work around the colors in cargo-whatfeatures. So that means that every invocation of CWF would have to be prefixed with `NO_COLOR=1` which is kind of a headache. (I have solved the problem for now by creating a shell function, which I will hopefully be able to remember exists. 😄)

**Comment by museun** [comment]
https://github.com/museun/cargo-whatfeatures/issues/71 I recently added a change to change the theme to use your terminal palette

**Comment by museun** [comment]
I just published 0.9.10 with the default theme change (to `palette`).

Sorry for the oversight, but I'm willing to discuss and implement most customability

**Comment by nk9** [comment]
Thanks very much! I've downloaded the latest version and it's working out of the box, no flags needed.

TBH, looking back at my other suggestions from before, I'm not sure it's worth the effort to add the color configurability. I think the utility is working sufficiently well now for my purposes. Happy to close this now, I really appreciate the quick turnaround!
