### ISSUE TITLE
Problems trying out 0.9.11

### ISSUE THREAD

**Issue by dholroyd** [museun/cargo-whatfeatures#79]
(My goal was to try and work out why a transitive dependency of my local crate is pulling openssl via reqwests when I thought I had features/default-features configured to use rustls.)

```
$ cargo whatfeatures --version
cargo-whatfeatures 0.9.11
```

First attempt after reading the help text, run in my project directory,

```
$ cargo whatfeatures Cargo.toml 
ERROR: failed to start `cargo metadata`: No such file or directory (os error 2)
```

So I thought that maybe it needs to be more clear that this is a local path, and so made sure the value is fully qualified,

```
$ cargo whatfeatures $PWD/Cargo.toml 
thread 'main' panicked at /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-whatfeatures-0.9.11/src/printer/workspace.rs:51:31:
called `Option::unwrap()` on a `None` value
```

I got the same results as above adding the `--manifest-path` option.

**Comment by museun** [comment]
You would use `--manifest-path` for that.

Normally, this tool is used to get the features of a crate from crates.io, so the syntax `cargo whatfeatures tokio` can be translated to the _current_ crate by doing `cargo whatfeatures .` (or `cargo whatfeatures ../some/crate/`

But since you tried it, is the `cwd` a valid crate? Does `cargo metadata --format-version=1` return some json? (`cargo metadata` also has a `--manifest-path`)

**Comment by museun** [comment]
Also, I see the problem. `manifest-path` takes a directory, not a `Cargo.toml` path. Such as the root path for the crate/workspace.

There is some logic internally for finding `Cargo.toml` based on this path, so I can add more logic to check to see if its a `[Cc]argo.toml` explicitly and resolve correctly.

**Comment by museun** [comment]
I pushed a new version, v0.9.12, that'll allow you to pass `Cargo.toml` to `--manifest-path`

**Comment by dholroyd** [comment]
0.9.12 addresses the error messages I was seeing, and exchanges them for `An empty tree was returned by cargo-metdata`.

Experimenting with `cargo metadata` directly:

```
$ cargo metadata --format-version=1
(produces json output)
```

```
$ cargo metadata --format-version=1 --manifest-path .
error: the manifest-path must be a path to a Cargo.toml file
```

```
$ cargo metadata --format-version=1 --manifest-path Cargo.toml
(produces json output)
```

```
$ cargo metadata --format-version=1 --manifest-path $PWD
error: the manifest-path must be a path to a Cargo.toml file
```

(Tangentially, I have now fixed the problem I was trying to debug by running whatfeatures in the first place; I had patched an intermediate dependency to have `reqwest = { .. default-features=false, .. }` in one of the workspace members, but it still had a dependency on `reqwest` in the workspace root - adding `default-features=false` there too got things working.)

**Comment by museun** [comment]
You can also use `cargo tree` for that use case: <https://doc.rust-lang.org/cargo/commands/cargo-tree.html> notably with the -e and -f flags
