### ISSUE TITLE
rustc 1.80 breaks older 'time' crate, preventing compile

### ISSUE THREAD

**Issue by damccull** [museun/cargo-whatfeatures#84]
Are you aware of this issue?
https://github.com/time-rs/time/issues/693

It's breaking older time crates on rust 1.80, but it's fixable by updating the time crate.

I can't get cargo-whatfeatures to cargo install because of this. Any chance you can fix it?

**Comment by museun** [comment]
I've published 0.9.13 which resolves this issue. Thanks for bringing it up.

Since burntsushi published their `jiff` time crate, I may switch over to it to reduce the chance of this happening again.

**Comment by damccull** [comment]
Thanks! I love this tool.
